### ISSUE TITLE
Add algorithm settings to debug view

### ISSUE THREAD

**Issue by jakubfiala** [hermetechnics/cellulare#6]

**Comment by imunita21** [comment]
@jakubfiala 
pridala som density, myslis, ze nam treba aj grid_size? 
to si bude vyzadovat recalculation lokacie vsetkych ucastnikov

**Comment by jakubfiala** [comment]
super! hm myslim ze grid size netreba, to je asi taky viac coarse parameter ktory nebude treba casto menit
